services:
  - type: web
    name: drf-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: api.settings
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DJANGO_ALLOWED_HOSTS
        value: drf-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: drf-db
          property: connectionString

databases:
  - name: drf-db
    databaseName: drf_db
    user: drf_user
